name: Build

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
          - macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2.4.0
      - name: Setup Yarn
        run: npm install -g yarn
      - name: Setup Rust (nightly)
        uses: dtolnay/rust-toolchain@nightly
      - name: Setup OpenSSL
        run: |
          vcpkg integrate install
          vcpkg install openssl:x64-windows-static-md
        if: matrix.os == 'windows-latest'
      - name: Download WinPcap Developer Pack
        run: |
          Invoke-WebRequest -OutFile WpdPack.zip https://www.winpcap.org/install/bin/WpdPack_4_1_2.zip
          7z x WpdPack.zip
          cp WpdPack/Lib/x64/Packet.lib src-tauri/Packet.lib
        if: matrix.os == 'windows-latest'
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: |
          yarn build
          yarn tauri build
      - name: Upload a build artifact
        uses: actions/upload-artifact@v2
        with:
          name: pcap2socks-gui-latest-${{ runner.os }}-amd64
          path: |
            ./src-tauri/target/release/bundle/dmg/pcap2socks*.dmg
            ./src-tauri/target/release/bundle/
